import { ComponentFixture, TestBed } from '@angular/core/testing';
import { Subject, of, throwError } from 'rxjs';
import { AdaptivePracticeApiService } from '../../../api/adaptive-practice-api.service';
import { AdaptivePracticeProgress } from './adaptive-practice-progress';
import type { TeacherAdaptiveAttemptsResponse, TeacherAdaptiveProgressResponse } from './adaptive-practice-progress.types';

describe('AdaptivePracticeProgress', () => {
  let fixture: ComponentFixture<AdaptivePracticeProgress>; let component: AdaptivePracticeProgress; let api: jasmine.SpyObj<AdaptivePracticeApiService>;
  const progress: TeacherAdaptiveProgressResponse = { state: 'in-progress', sourceStatus: 'current', submissionId: 'submission-1', sessionId: 'session-1', summary: { totalActivities: 2, improvedActivities: 1, progressPercentage: 50, totalAttempts: 3, lastPracticedAt: '2026-01-01T00:00:00Z' }, skills: [{ skillId: 'ORGANIZATION', label: 'Coherence & Flow', originalEarnedPoints: 11, originalMaximumPoints: 20, originalPercentage: 55, activityId: 'activity-1', attemptCount: 3, latestScore: 68, bestScore: 70, improved: true, lastAttemptAt: '2026-01-01T00:00:00Z' }] };
  const history: TeacherAdaptiveAttemptsResponse = { sessionId: 'session-1', activityId: 'activity-1', attempts: [{ id: 'attempt-1', attemptNumber: 1, status: 'ready', response: 'Synthetic response.', practiceScore: 70, improved: true, summary: 'Summary', strength: 'Strength', nextImprovement: 'Next', checklist: [{ item: 'Criterion', met: true, feedback: 'Met' }], suggestedRevision: 'Revision', attemptedAt: '2026-01-01T00:00:00Z' }], pagination: { page: 1, limit: 10, total: 1, totalPages: 1, hasMore: false } };
  beforeEach(async () => { api = jasmine.createSpyObj<AdaptivePracticeApiService>('AdaptivePracticeApiService', ['getTeacherProgress', 'getTeacherActivityAttempts']); api.getTeacherProgress.and.returnValue(of({ success: true, data: progress })); api.getTeacherActivityAttempts.and.returnValue(of({ success: true, data: history })); await TestBed.configureTestingModule({ imports: [AdaptivePracticeProgress], providers: [{ provide: AdaptivePracticeApiService, useValue: api }] }).compileComponents(); fixture = TestBed.createComponent(AdaptivePracticeProgress); component = fixture.componentInstance; });
  it('renders loading and not-started states', () => { const pending = new Subject<{ success: boolean; data: TeacherAdaptiveProgressResponse }>(); api.getTeacherProgress.and.returnValue(pending); component.submissionId = 'pending'; fixture.detectChanges(); expect(fixture.nativeElement.querySelector('.skeleton')).toBeTruthy(); pending.next({ success: true, data: { ...progress, state: 'not-started', sessionId: null, skills: [], summary: { totalActivities: 0, improvedActivities: 0, progressPercentage: 0, totalAttempts: 0, lastPracticedAt: null } } }); fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('has not started'); });
  it('keeps original and best scores separate and treats exactly 70 as improved', () => { component.submissionId = 'submission-1'; fixture.detectChanges(); const text = fixture.nativeElement.textContent; expect(text).toContain('Original assessment at generation'); expect(text).toContain('55%'); expect(text).toContain('Best practice'); expect(text).toContain('70%'); expect(text).toContain('Improved'); });
  it('renders the outdated source warning', () => { api.getTeacherProgress.and.returnValue(of({ success: true, data: { ...progress, sourceStatus: 'outdated' } })); component.submissionId = 'outdated'; fixture.detectChanges(); expect(fixture.nativeElement.textContent).toContain('earlier assessment version'); });
  it('lazy-loads attempt history once and contains card errors', () => { component.submissionId = 'submission-1'; fixture.detectChanges(); component.toggleHistory(progress.skills[0]); fixture.detectChanges(); expect(api.getTeacherActivityAttempts).toHaveBeenCalledOnceWith('session-1', 'activity-1', 1, 10); expect(fixture.nativeElement.textContent).toContain('Synthetic response'); component.toggleHistory(progress.skills[0]); component.toggleHistory(progress.skills[0]); expect(api.getTeacherActivityAttempts).toHaveBeenCalledTimes(1); });
  it('keeps monitoring errors local and contains no teacher actions', () => { api.getTeacherProgress.and.returnValue(throwError(() => new Error('provider detail'))); component.submissionId = 'error'; fixture.detectChanges(); const text = fixture.nativeElement.textContent; expect(text).toContain('could not be loaded'); expect(text).not.toMatch(/Generate|Check My Writing|Reset|Edit/); });
  it('ignores late progress from the previous submission and clears histories', () => { const old = new Subject<{ success: boolean; data: TeacherAdaptiveProgressResponse }>(); api.getTeacherProgress.and.returnValues(old, of({ success: true, data: { ...progress, submissionId: 'submission-2' } })); component.submissionId = 'submission-1'; component.histories = { old: { open: true, loading: false, error: '', attempts: [], page: 0, hasMore: false } }; component.submissionId = 'submission-2'; old.next({ success: true, data: progress }); expect(component.progress?.submissionId).toBe('submission-2'); expect(Object.keys(component.histories)).toEqual([]); });
});
