import {CommonModule} from '@angular/common';
import {Component,inject,signal} from '@angular/core';
import {FormsModule} from '@angular/forms';
import {RetentionAdminApiService,type Page} from '../../api/retention-admin-api.service';
import {AlertService} from '../../services/alert.service';
type Kind='referrals'|'bonus-rewards'|'milestones'|'institutions';
type Owner={_id:string;email:string;displayName?:string};
type InstitutionRow={_id:string;name:string;status:string;seatLimit?:number;activeTeachers?:number;wallet?:{monthlyCredits:number;monthlyCreditsUsed:number}};
@Component({selector:'app-admin-retention-operations',standalone:true,imports:[CommonModule,FormsModule],templateUrl:'./admin-retention-operations.html',styleUrl:'./admin-retention-operations.css'})
export class AdminRetentionOperations{
 private alerts=inject(AlertService);
 private api=inject(RetentionAdminApiService);kinds:Kind[]=['referrals','bonus-rewards','milestones','institutions'];labels:Record<Kind,string>={referrals:'Referral Operations','bonus-rewards':'Bonus Rewards',milestones:'Milestones',institutions:'Institutions'};statuses=['ACTIVE','PAST_DUE','SUSPENDED','CANCELED'];kind=signal<Kind>('referrals');page=signal(1);data=signal<Page<any>|null>(null);error=signal('');saving=signal(false);viewing=signal<any|null>(null);search='';ownerSearch='';ownerCandidates=signal<Owner[]>([]);selectedOwner=signal<Owner|null>(null);editing=signal<InstitutionRow|null>(null);create={name:'',seatLimit:1,monthlyCredits:0,status:'ACTIVE',cycleStart:'',cycleEnd:''};edit={seatLimit:1,monthlyCredits:0,status:'ACTIVE'};
 async ngOnInit(){await this.load('referrals')}async load(kind:Kind){if(this.kind()!==kind){this.page.set(1);this.editing.set(null);this.viewing.set(null)}this.kind.set(kind);try{this.data.set(await this.api.operations(kind,this.page(),this.search.trim()));this.error.set('')}catch(e:any){this.error.set(e?.error?.message||'Operations could not be loaded.')}}searchOperations(){this.page.set(1);return this.load(this.kind())}previous(){this.page.update(x=>x-1);return this.load(this.kind())}next(){this.page.update(x=>x+1);return this.load(this.kind())}
 async findOwners(){try{this.ownerCandidates.set(await this.api.ownerCandidates(this.ownerSearch.trim()));this.selectedOwner.set(null);this.error.set('')}catch(e:any){this.error.set(e?.error?.message||'Eligible owners could not be loaded.')}}selectOwner(owner:Owner){this.selectedOwner.set(owner);this.ownerCandidates.set([])}validCommercial(seats:number,credits:number){if(!Number.isInteger(seats)||seats<1){this.error.set('Seat limit must be a positive integer.');return false}if(!Number.isInteger(credits)||credits<0){this.error.set('Monthly shared credits must be a nonnegative integer.');return false}return true}
 async createInstitution(){const owner=this.selectedOwner();if(!this.create.name.trim()){this.error.set('Institution name is required.');return}if(!owner){this.error.set('Select an owner from the eligible teacher lookup.');return}if(!this.validCommercial(this.create.seatLimit,this.create.monthlyCredits))return;this.saving.set(true);try{await this.api.provisionInstitution({name:this.create.name.trim(),ownerUserId:owner._id,seatLimit:this.create.seatLimit,monthlyCredits:this.create.monthlyCredits,status:this.create.status,...(this.create.cycleStart?{cycleStart:new Date(this.create.cycleStart).toISOString()}:{}),...(this.create.cycleEnd?{cycleEnd:new Date(this.create.cycleEnd).toISOString()}:{})});this.create={name:'',seatLimit:1,monthlyCredits:0,status:'ACTIVE',cycleStart:'',cycleEnd:''};this.selectedOwner.set(null);this.ownerSearch='';await this.load('institutions');this.alerts.showSuccess('Institution provisioned','The institution is ready and its owner has been synchronized.')}catch(e:any){const message=e?.error?.message||'Institution could not be created.';this.error.set(message);this.alerts.showError('Institution provisioning failed',message)}finally{this.saving.set(false)}}
 beginEdit(row:InstitutionRow){this.editing.set(row);this.edit={seatLimit:row.seatLimit??Math.max(row.activeTeachers||1,1),monthlyCredits:row.wallet?.monthlyCredits??0,status:row.status}}viewDetails(row:any){this.viewing.set(row)}async saveInstitution(){const row=this.editing();if(!row||!this.validCommercial(this.edit.seatLimit,this.edit.monthlyCredits))return;this.saving.set(true);try{await this.api.updateInstitution(row._id,{...this.edit});this.editing.set(null);await this.load('institutions');this.alerts.showSuccess('Institution updated','Commercial institution settings were saved successfully.')}catch(e:any){const message=e?.error?.message||'Institution could not be updated.';this.error.set(message);this.alerts.showError('Institution update failed',message)}finally{this.saving.set(false)}}title(r:any){return r.name||r.userId?.displayName||r.referredUserId?.displayName||r.milestoneKey||r._id}detail(r:any){if(this.kind()==='institutions')return`${r.activeTeachers||0} active · ${r.wallet?.monthlyCreditsUsed||0}/${r.wallet?.monthlyCredits||0} credits used`;return`${r.eventType||r.qualificationType||r.rewardStatus||''} ${r.amount??''}`.trim()}
}
