import {HttpClient} from '@angular/common/http';import{Injectable}from'@angular/core';import{firstValueFrom}from'rxjs';import{environment}from'../../environments/environment';
export type RewardRule={enabled:boolean;amount:number|null;repeatPolicy?:string};export type MilestoneRule={key:string;title:string;description:string;metricType:string;enabled:boolean;threshold:number};
export type RetentionSettings={version:number;referral:{referrerRewardCredits:number;referredRewardCredits:number;maxRewardedReferralsPerReferrer:number|null};bonusRewards:Record<string,RewardRule>;milestones:MilestoneRule[];weeklySummary:{enabled:boolean;day:string|null;hour:number|null;timezone:string|null};creditNudges:{thresholds:number[];configurable:boolean};institution:Record<string,unknown>};
export type RetentionSettingsPatch={version:number;referral:RetentionSettings['referral'];bonusRewards:Record<string,{enabled:boolean;amount:number|null}>;milestones:Array<{key:string;enabled:boolean;threshold:number}>;weeklySummary:RetentionSettings['weeklySummary'];creditNudges:{thresholds:number[]}};
const optionalNumber=(value:unknown):number|null=>value==null||value===''?null:Number(value);
export function buildRetentionSettingsPatch(value:RetentionSettings):RetentionSettingsPatch{return{version:value.version,referral:{referrerRewardCredits:Number(value.referral.referrerRewardCredits),referredRewardCredits:Number(value.referral.referredRewardCredits),maxRewardedReferralsPerReferrer:optionalNumber(value.referral.maxRewardedReferralsPerReferrer)},bonusRewards:Object.fromEntries(Object.entries(value.bonusRewards).map(([key,rule])=>[key,{enabled:Boolean(rule.enabled),amount:optionalNumber(rule.amount)}])),milestones:value.milestones.map(rule=>({key:rule.key,enabled:Boolean(rule.enabled),threshold:Number(rule.threshold)})),weeklySummary:{enabled:Boolean(value.weeklySummary.enabled),day:value.weeklySummary.day||null,hour:optionalNumber(value.weeklySummary.hour),timezone:value.weeklySummary.timezone?.trim()||null},creditNudges:{thresholds:value.creditNudges.thresholds.map(Number)}}}
export type Page<T>={items:T[];total:number;page:number;limit:number};
type R<T>={success:boolean;data:T};@Injectable({providedIn:'root'})export class RetentionAdminApiService{constructor(private http:HttpClient){}async get(){return(await firstValueFrom(this.http.get<R<RetentionSettings>>(`${environment.apiUrl}/admin/retention-settings`))).data}async save(value:RetentionSettings){return(await firstValueFrom(this.http.patch<R<RetentionSettings>>(`${environment.apiUrl}/admin/retention-settings`,buildRetentionSettingsPatch(value)))).data}
async operations<T>(kind:'referrals'|'bonus-rewards'|'milestones'|'institutions',page=1,search=''){return(await firstValueFrom(this.http.get<R<Page<T>>>(`${environment.apiUrl}/admin/${kind}`,{params:{page,limit:25,...(search?{search}:{})}}))).data}
async milestoneOperations(){return(await firstValueFrom(this.http.get<R<{counts:Array<{_id:string;count:number}>;recent:unknown[]}>>(`${environment.apiUrl}/admin/milestones`))).data}
async ownerCandidates(search:string){return(await firstValueFrom(this.http.get<R<Array<{_id:string;email:string;displayName?:string}>>>(`${environment.apiUrl}/admin/institution-owner-candidates`,{params:{search}}))).data}
async provisionInstitution(payload:Record<string,unknown>){return firstValueFrom(this.http.post(`${environment.apiUrl}/institutions/provision`,payload))}
async updateInstitution(id:string,payload:Record<string,unknown>){return firstValueFrom(this.http.patch(`${environment.apiUrl}/admin/institutions/${encodeURIComponent(id)}`,payload))}}
